USE [master]
GO
/****** Object:  Database [BDEmpresa]    Script Date: 9/17/2024 6:43:42 PM ******/
CREATE DATABASE [BDEmpresa]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BDEmpresa', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.DESARROLLO\MSSQL\DATA\BDEmpresa.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'BDEmpresa_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.DESARROLLO\MSSQL\DATA\BDEmpresa_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [BDEmpresa] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BDEmpresa].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [BDEmpresa] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [BDEmpresa] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [BDEmpresa] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [BDEmpresa] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [BDEmpresa] SET ARITHABORT OFF 
GO
ALTER DATABASE [BDEmpresa] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [BDEmpresa] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [BDEmpresa] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [BDEmpresa] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [BDEmpresa] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [BDEmpresa] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [BDEmpresa] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [BDEmpresa] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [BDEmpresa] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [BDEmpresa] SET  ENABLE_BROKER 
GO
ALTER DATABASE [BDEmpresa] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [BDEmpresa] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [BDEmpresa] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [BDEmpresa] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [BDEmpresa] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [BDEmpresa] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [BDEmpresa] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [BDEmpresa] SET RECOVERY FULL 
GO
ALTER DATABASE [BDEmpresa] SET  MULTI_USER 
GO
ALTER DATABASE [BDEmpresa] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [BDEmpresa] SET DB_CHAINING OFF 
GO
ALTER DATABASE [BDEmpresa] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [BDEmpresa] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [BDEmpresa] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [BDEmpresa] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'BDEmpresa', N'ON'
GO
ALTER DATABASE [BDEmpresa] SET QUERY_STORE = ON
GO
ALTER DATABASE [BDEmpresa] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [BDEmpresa]
GO
/****** Object:  Table [dbo].[Categoria]    Script Date: 9/17/2024 6:43:43 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Categoria](
	[NoCategoria] [int] IDENTITY(1,1) NOT NULL,
	[nombreCategoria] [nvarchar](40) NOT NULL,
	[descripcion] [nvarchar](40) NULL,
 CONSTRAINT [PK_Categoria] PRIMARY KEY CLUSTERED 
(
	[NoCategoria] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Producto]    Script Date: 9/17/2024 6:43:43 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Producto](
	[NoProducto] [int] IDENTITY(1,1) NOT NULL,
	[NoCategoria] [int] NOT NULL,
	[nombreProducto] [nvarchar](40) NOT NULL,
	[descripcion] [nvarchar](40) NULL,
	[stock] [int] NULL,
	[precioVenta] [money] NULL,
	[estado] [bit] NOT NULL,
 CONSTRAINT [PK_Producto] PRIMARY KEY CLUSTERED 
(
	[NoProducto] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Producto] ADD  DEFAULT ((1)) FOR [estado]
GO
ALTER TABLE [dbo].[Producto]  WITH NOCHECK ADD  CONSTRAINT [FK_Producto_Categoria] FOREIGN KEY([NoCategoria])
REFERENCES [dbo].[Categoria] ([NoCategoria])
GO
ALTER TABLE [dbo].[Producto] CHECK CONSTRAINT [FK_Producto_Categoria]
GO
USE [master]
GO
ALTER DATABASE [BDEmpresa] SET  READ_WRITE 
GO
